--TASK1--

--Q1--
SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE SALARY BETWEEN 6000 AND 8000

--Q2--
SELECT EMPLOYEE_ID,FIRST_NAME
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 80

--Q3--
SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE JOB_ID IN('IT_PROG','SH_CLERK','PU_CLERK')

--Q4--
SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NULL

--TASK2-- 

--Q1--
SELECT UPPER(FIRST_NAME),LOWER(JOB_ID)
FROM HR.EMPLOYEES

--Q2--
SELECT 
    FIRST_NAME || JOB_ID,
    LENGTH(FIRST_NAME) AS name_length,
    INSTR(FIRST_NAME, 'A') AS position_of_A
    FROM HR.EMPLOYEES 
    
 --Q3--   
SELECT HIRE_DATE,EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2003;
   
--Q4--   
SELECT TO_CHAR(HIRE_DATE,'DD Month, YYYY') as date_formatted,FIRST_NAME
FROM HR.EMPLOYEES;

--Q5--
SELECT CONCAT('$',SALARY),FIRST_NAME
FROM HR.EMPLOYEES
WHERE FIRST_NAME = 'Neena'

--Q6--
SELECT EMPLOYEE_ID,LAST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '%A%'

--Q7--
SELECT EMPLOYEE_ID,
       SUBSTR(FIRST_NAME, 3)
FROM HR.EMPLOYEES


--TASK3--

--Q1--
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       SALARY AS before_increment,
       (SALARY + (SALARY  * 0.15)) AS after_increment,
       ((SALARY + (SALARY  * 0.15)) - SALARY) AS INCREMENTED_AMOUNT
FROM HR.EMPLOYEES

--Q2--
SELECT HIRE_DATE,
       TO_CHAR(HIRE_DATE,'Day') as day_of_the_week
FROM HR.EMPLOYEES
ORDER BY day_of_the_week ASC
       
--Q3--
SELECT DEPARTMENT_ID,
       MANAGER_ID,
       ROUND(COMMISSION_PCT,1) AS COMMISSION
FROM HR.EMPLOYEES       
    
    
 --Q4--      
SELECT EMPLOYEE_ID,
       COMMISSION_PCT
FROM HR.EMPLOYEES  
WHERE (DEPARTMENT_ID <> 90 OR  DEPARTMENT_ID <> 100) AND  COMMISSION_PCT > 0 

--Q5--
SELECT JOB_ID,
       JOB_TITLE
FROM HR.JOBS  
WHERE MIN_SALARY BETWEEN 8000 AND 15000 

--Q6--
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID
FROM HR.EMPLOYEES
WHERE (EMPLOYEE_ID BETWEEN 100 AND 150) AND (DEPARTMENT_ID BETWEEN 90 AND 100)

--Q7--
SELECT (SALARY + (COMMISSION_PCT * SALARY)) AS TOTAL_SALARY,
       COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL

























