--task2--
CREATE TABLE JOBS( 
JOB_ID VARCHAR2(10 BYTE) NOT NULL,
JOB_TITLE VARCHAR2(35 BYTE),
MIN_SALARY NUMBER(6,0),
MAX_SALARY NUMBER(6,0),
PRIMARY KEY(JOB_ID)
);
CREATE TABLE JOB_HISTORY( 
EMPLOYEE_ID NUMBER(6,0)NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10 BYTE) NOT NULL,
DEPARTMENT_ID NUMBER(4,0)NOT NULL,
PRIMARY KEY(JOB_ID)
);

--task3--
ALTER TABLE JOBS MODIFY JOB_ID INT;

--task4---
 ALTER TABLE JOB_HISTORY
 MODIFY JOB_ID INT;
 ALTER TABLE JOB_HISTORY
 ADD FOREIGN KEY (JOB_ID)
 REFERENCES JOBS(JOB_ID);

--task5--
INSERT INTO JOBS VALUES('12','manager',0,60050,14);

--task6--
ALTER TABLE JOBS ADD JOBS_NATURE VARCHAR(10);

--task7--
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID	NUMBER(6,0),
FIRST_NAME	VARCHAR2(20 BYTE),
LAST_NAME	VARCHAR2(25 BYTE),
EMAIL	VARCHAR2(25 BYTE),
PHONE_NUMBER	VARCHAR2(20 BYTE),
HIRE_DATE	DATE,
JOB_ID	VARCHAR2(10 BYTE),
SALARY	NUMBER(8,2),
COMMISSION_PCT	NUMBER(2,2),
MANAGER_ID	NUMBER(6,0),
DEPARTMENT_ID	NUMBER(4,0);
PRIMARY KEY(EMPLOYEE_ID));


--task8--
 ALTER TABLE JOB_HISTORY;
 ADD FOREIGN KEY (EMPLOYEE_ID)
 REFERENCES EMPLOYEES(EMPLOYEE_ID);
 
--task9--
ALTER TABLE JOBS
DROP COLUMN JOB_NATURE;

--task10--
ALTER table EMPLOYEE
ADD CONSTRAINT F_N_UPPER CHECK(UPPER(FIRST_NAME) = FIRST_NAME);

--task11--
ALTER table EMPLOYEE
ADD CONSTRAINT CHECK_SALARY UNIQUE(SALARY);

--task12--
ALTER table EMPLOYEE
MODIFY PHONE_NUMBER VARCHAR2(20 BYTE) NOT NULL;

--task13--
 INSERT INTO employees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (102, 'aiman', 'AIN', 'aiman@example.com', '0333219098', TO_DATE('2023-09-08', 'YYYY-MM-DD'), 'IT_PROG', 60500, NULL, 57, 20);

 --task14--
 ALTER TABLE JOB_HISTORY 
DROP CONSTRAINTS SYS_C007021;
ALTER TABLE EMPLOYEES
DROP CONSTRAINTS SYS_C007009;
ALTER TABLE EMPLOYEES
ADD PRIMARY KEY(EMPLOYEE_ID,JOB_ID);
 
--task15--
 CREATE UNIQUE INDEX INDX_JOB_ID ON JOB_HISTORY(JOB_ID);

--task16--
DELETE FROM EMPLOYEES;

























