
--TASK1--
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID;

--TASK2--
SELECT  D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME  
HAVING  COUNT(E.EMPLOYEE_ID) > 2;

--TASK3--
SELECT *
FROM HR.EMPLOYEES E
WHERE E.SALARY < (SELECT AVG(SALARY) FROM HR.EMPLOYEES  WHERE DEPARTMENT_ID IS NOT NULL); 


--TASK4--
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, J.JOB_TITLE, L.CITY
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID 
JOIN HR.JOBS J ON J.JOB_ID = E.JOB_ID 
WHERE E.SALARY*12 = 60000;


--TASK5--
SELECT  DISTINCT(E.FIRST_NAME),E.LAST_NAME
FROM HR.EMPLOYEES E 
JOIN HR.EMPLOYEES ER ON E.EMPLOYEE_ID = ER.MANAGER_ID;


--TASK6--
SELECT  E.EMPLOYEE_ID
FROM HR.EMPLOYEES E 
WHERE E.DEPARTMENT_ID IN (10,20,30) OR E.SALARY > 70000;


--TASK7--
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS NULL OR D.DEPARTMENT_ID IS NOT NULL;

--TASK8-- 
SELECT D.DEPARTMENT_NAME, AVG(E.SALARY), COUNT(E.EMPLOYEE_ID)
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE  E.COMMISSION_PCT > 0
GROUP BY D.DEPARTMENT_NAME;


--TASK9--
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
WHERE FIRST_NAME LIKE '%Z%';


--TASK10-- 
SELECT J.JOB_ID, JJ.JOB_ID 
FROM HR.JOBS J
JOIN HR.JOB_HISTORY JJ ON J.JOB_ID = JJ.JOB_ID; 



